### ISSUE TITLE
Invalid last-child / last-type / ntn:x selectors

### ISSUE THREAD

**Issue by Gomah** [Gomah/bulmil#25]
As bulma components & elements are wrapped in Stencil components, some selectors might not work.

e.g for Buttons:

```scss
.buttons {
  .button {
    &:not(:last-child):not(.is-fullwidth) {
      margin-right: 0.5rem;
    }
  }
}
```

Work around:

```scss
b-buttons {
  b-button {
    &:not(:last-child):not(.is-fullwidth) {
      margin-right: 0.5rem;
    }
  }
}
```
